### PR TITLE
Update manual.txt with Nginx specific instructions

### PR DESCRIPTION
**Pull request by drdee**
We discovered this issue the hard way :)

### CODE REVIEW

**Comment by ignacio** [comment]
Could you clarify? I'm curious about the need to `encode_keep_buffer = false`.
Looking at the code, it is safe to leave it as is, as long as you don't access a Lua VM concurrently from multiple threads.

**Comment by drdee** [comment]
The problem is cjson's `encode_buf`. Specifically, it's because it is being shared between Lua VM instances on workers. nginx IS single threaded, but evented, and workers share the same `lua_State` object. This is all fine, so long as worker never yields. From the nginx lua docs:

> You can also share changeable data among all the concurrent requests of each nginx worker process as long as there is no nonblocking I/O operations (including ngx.sleep) in the middle of your calculations. As long as you do not give the control back to the nginx event loop and ngx_lua's light thread scheduler (even implicitly), there can never be any race conditions in between. For this reason, always be very careful when you want to share changeable data on the worker level. Buggy optimizations can easily lead to hard-to-debug race conditions under load.

http://wiki.nginx.org/HttpLuaModule#Data_Sharing_within_an_Nginx_Worker

This is exactly what we we saw when testing this in out staging and ran Apache Benchmark while generating a high load. The beginning of the section:

> To globally share data among all the requests handled by the same nginx worker process, encapsulate the shared data into a Lua module, use the Lua require builtin to import the module, and then manipulate the shared data in Lua. This works because required Lua modules are loaded only once and all coroutines will share the same copy of the module (both its code and data). 

Because cjson is being `require`d in by our lua module, the module state is being shared across the worker. This means if the running coroutine yields for any reason, another coroutine will resume execution and potentially change the state of the module while it's in use. If the coroutine completes execution without yielding, everything is fine. But we do yield. Any blocking socket operation, sleep, or timeout will cause the calling coroutine to yield.

I copied this explanation from our internal ticket, many thanks to csfrancis for providing this explanation.

So that's also why I did not change the code but added it as a note to the `manual.txt` as I can imagine that other people might run into the same issue.

**Comment by ignacio** [comment]
Thanks for the detailed explanation. So if I understood correctly, you have multiple coroutines running within a Lua VM. 
I still don't understand how yielding can become a problem, since the buffer is used fully in json_encode. There can't be any concurrent access. You can't have two calls to encode at the same time.
Could it be that disabling buffer reuse just made the actual problem harder to reproduce?

**Comment by drdee** [comment]
Yeah I am back tracking on that explanation as well and going to dig more. We are using lua-cjson in combination with the lua-nginx-module and wrapping the `json_encode` call in a `pcall`.

**Comment by drdee** [comment]
False alarm, the bug was very subtle (buffer overrun of 1 byte) in our own code.

**Comment by ignacio** [comment]
Good! I'm glad you found the actual bug, and thanks for updating this PR.

**Pull request closed without merging**
